CartPole-v1:
  n_timesteps: !!float 1e5
  policy: 'CustomDQNPolicy'
  learning_rate: !!float 1e-3
  buffer_size: 50000
  exploration_fraction: 0.1
  exploration_final_eps: 0.02
  prioritized_replay: True